name: Deploy on dev

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'dev'
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install NPM dependencies
        run: npm install
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Build NextJS app
        run: npm run build
      - name: Start NextJS app
        run: pm2 reload dev
