name: Deploy on dev

env:
  GITHUB_WORKSPACE: /wwwdev

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'BastienScanu/bastien-v2'
          ref: 'dev'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install NPM dependencies
        run: npm install
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Build NextJS app
        run: npm run build
      - name: Install PM2
        run: npm i pm2
      - name: Start NextJS app
        run: pm2 start npm run start
