name: Deploy on dev

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: dev-runner
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'dev'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install NPM dependencies
        run: npm ci
      - name: Build NextJS app
        run: npm run build
      - name: Start NextJS app
        run: pm2 reload dev
