name: Deploy on prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
          path: prod
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install NPM dependencies
        working-directory: ./prod
        run: npm ci
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Build NextJS app
        working-directory: ./prod
        run: npm run build
      - name: Start NextJS app
        run: pm2 reload prod
